runtime: php81

# Environment variables for Google Cloud
env_variables:
  # Database connection (Cloud SQL Unix socket)
  DB_HOST: '/cloudsql/fit-and-brawl-gym:asia-southeast1:fit-brawl-db'
  DB_NAME: 'fit_and_brawl_gym'
  DB_USER: 'root'
  DB_PASS: 'FitAndBrawl123!'
  DB_PORT: '3306'

  # Application URL (update this to your App Engine URL)
  APP_URL: 'https://fit-and-brawl-gym.appspot.com'

  # Email settings (Gmail)
  EMAIL_HOST: 'smtp.gmail.com'
  EMAIL_PORT: '587'
  EMAIL_USER: 'mikellandreirazon@gmail.com'
  EMAIL_PASS: 'hgog lwge gdtd hvut'  # ← Gmail App Password (16 chars with spaces)

  # Cloud Run service URL for receipt rendering (update after deploying Cloud Run)
  RECEIPT_RENDERER_URL: 'https://receipt-renderer-441193964417.asia-southeast1.run.app'

  # Google Cloud Platform settings
  GCP_PROJECT_ID: 'fit-and-brawl-gym'
  GCP_STORAGE_BUCKET: 'fit-brawl-uploads'

# Handlers for routing
handlers:
  # Serve static files from public directory (CSS, JS, images, etc.)
  - url: /public/(.*\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2|ttf|eot|pdf))
    static_files: public/\1
    upload: public/.*\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2|ttf|eot|pdf)
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=3600'

  # Serve static files from images directory
  - url: /images/(.*\.(png|jpg|jpeg|gif|svg|webp))
    static_files: images/\1
    upload: images/.*\.(png|jpg|jpeg|gif|svg|webp)
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=3600'

  # Let PHP handle all other requests (including health.php, test.php, all .php files)
  - url: /.*
    script: auto
    secure: always

# Automatic scaling configuration (stays within free tier)
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6
  min_instances: 0
  max_instances: 2
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms

# Enable Cloud SQL (update with your instance connection name)
beta_settings:
  cloud_sql_instances: fit-and-brawl-gym:asia-southeast1:fit-brawl-db

# Health check (simple endpoint with no dependencies)
liveness_check:
  path: "/health.php"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health.php"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
