# Cloud Build configuration for deploying receipt renderer to Cloud Run

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/receipt-renderer:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/receipt-renderer:$BUILD_ID'
      - './server-renderer'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/receipt-renderer:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/receipt-renderer:$BUILD_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'receipt-renderer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/receipt-renderer:latest'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/receipt-renderer:latest'
  - 'gcr.io/$PROJECT_ID/receipt-renderer:$BUILD_ID'

timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
