#!/bin/bash
echo "íº€ Manual Deployment to Production"
echo "=================================="
echo ""
echo "Run these commands on your EC2 server (54.227.103.23):"
echo ""
echo "1. Pull latest code:"
echo "   cd /home/ec2-user/fit-brawl"
echo "   git pull origin main"
echo ""
echo "2. Update Docker container:"
echo "   docker exec fitbrawl_web bash -c 'cd /var/www/html && git pull origin main'"
echo ""
echo "3. Install dependencies (if composer.json changed):"
echo "   docker exec fitbrawl_web composer install --no-dev --optimize-autoloader"
echo ""
echo "4. Restart server-renderer (if needed):"
echo "   pkill -f 'node.*server.js'"
echo "   cd /home/ec2-user/fit-brawl/server-renderer && nohup node server.js > /tmp/renderer.log 2>&1 &"
echo ""
echo "=================================="
echo "âœ… Copy these commands and run them on your server"
