<?php
/**
 * Automatic Encryption Setup Script
 * 
 * This script automatically sets up AES-256 encryption for your local environment.
 * Run this ONCE after pulling code: php setup_encryption.php
 * 
 * What it does:
 * 1. Checks if encryption key exists in config.php
 * 2. Generates key if missing
 * 3. Runs database migration (adds email_encrypted column)
 * 4. Verifies everything is working
 * 
 * @author Development Team
 * @version 1.0.0
 */

// Color output functions
function colorOutput($text, $color) {
    $colors = [
        'red' => "\033[0;31m",
        'green' => "\033[0;32m",
        'yellow' => "\033[1;33m",
        'blue' => "\033[0;34m",
        'cyan' => "\033[0;36m",
        'reset' => "\033[0m"
    ];
    
    if (PHP_OS_FAMILY === 'Windows') {
        return $text; // Windows CMD doesn't support ANSI colors well
    }
    
    return ($colors[$color] ?? '') . $text . $colors['reset'];
}

function printHeader($text) {
    echo "\n" . str_repeat("=", 60) . "\n";
    echo colorOutput("  " . $text, 'cyan') . "\n";
    echo str_repeat("=", 60) . "\n\n";
}

function printSuccess($text) {
    echo colorOutput("✅ ", 'green') . $text . "\n";
}

function printError($text) {
    echo colorOutput("❌ ", 'red') . $text . "\n";
}

function printWarning($text) {
    echo colorOutput("⚠️  ", 'yellow') . $text . "\n";
}

function printInfo($text) {
    echo colorOutput("ℹ️  ", 'blue') . $text . "\n";
}

// Start setup
printHeader("AES-256 Encryption Auto-Setup");

echo "This script will set up encryption for your local environment.\n";
echo "It's safe to run multiple times - it won't break anything!\n\n";

// Step 1: Check if config.php exists
printInfo("Step 1: Checking configuration file...");

$configPath = __DIR__ . '/includes/config.php';

if (!file_exists($configPath)) {
    printError("Config file not found: includes/config.php");
    printError("Make sure you're in the project root directory.");
    exit(1);
}

// Read config file
$configContent = file_get_contents($configPath);

// Step 2: Check if encryption key exists
printInfo("Step 2: Checking encryption key...");

if (strpos($configContent, 'ENCRYPTION_KEY') !== false && 
    strpos($configContent, 'hex2bin') !== false) {
    printSuccess("Encryption key already configured!");
} else {
    printWarning("Encryption key not found. Generating new key...");
    
    // Generate new 256-bit key
    $key = bin2hex(random_bytes(32));
    
    echo "\n";
    echo colorOutput("Generated 256-bit encryption key:", 'yellow') . "\n";
    echo colorOutput($key, 'cyan') . "\n\n";
    
    // Add key to config.php (before the closing PHP tag)
    $keyDefinition = "\n// AES-256 Encryption Key (Auto-generated by setup_encryption.php)\n";
    $keyDefinition .= "if (!getenv('ENCRYPTION_KEY')) {\n";
    $keyDefinition .= "    define('ENCRYPTION_KEY', hex2bin('$key'));\n";
    $keyDefinition .= "}\n";
    
    // Find the last ?> or end of file
    if (strpos($configContent, '?>') !== false) {
        $configContent = str_replace('?>', $keyDefinition . '?>', $configContent);
    } else {
        $configContent .= $keyDefinition;
    }
    
    file_put_contents($configPath, $configContent);
    printSuccess("Encryption key added to includes/config.php");
}

// Step 3: Check database connection
printInfo("Step 3: Checking database connection...");

require_once __DIR__ . '/includes/db_connect.php';

if (!$conn) {
    printError("Database connection failed!");
    printError("Please check your database configuration in includes/db_connect.php");
    exit(1);
}

printSuccess("Database connected!");

// Step 4: Check if migration is needed
printInfo("Step 4: Checking database structure...");

$result = $conn->query("SHOW COLUMNS FROM users LIKE 'email_encrypted'");

if ($result && $result->num_rows > 0) {
    printSuccess("Database already has email_encrypted column!");
} else {
    printWarning("email_encrypted column not found. Running migration...");
    
    // Read and execute migration SQL
    $migrationFile = __DIR__ . '/database/migrations/add_encryption.sql';
    
    if (file_exists($migrationFile)) {
        $sql = file_get_contents($migrationFile);
        
        // Execute migration
        if ($conn->query("ALTER TABLE users ADD COLUMN IF NOT EXISTS email_encrypted TEXT AFTER email")) {
            printSuccess("Migration completed! email_encrypted column added.");
        } else {
            printError("Migration failed: " . $conn->error);
            exit(1);
        }
    } else {
        printWarning("Migration file not found. Creating column manually...");
        
        if ($conn->query("ALTER TABLE users ADD COLUMN email_encrypted TEXT AFTER email")) {
            printSuccess("email_encrypted column added successfully!");
        } else {
            printError("Failed to add column: " . $conn->error);
            exit(1);
        }
    }
}

// Step 5: Check if data needs to be encrypted
printInfo("Step 5: Checking if existing data needs encryption...");

$result = $conn->query("SELECT COUNT(*) as total, 
                        SUM(CASE WHEN email_encrypted IS NOT NULL THEN 1 ELSE 0 END) as encrypted 
                        FROM users");
$stats = $result->fetch_assoc();

if ($stats['total'] > 0 && $stats['encrypted'] == 0) {
    printWarning("Found {$stats['total']} users without encrypted emails.");
    echo "\n";
    echo "Would you like to encrypt existing user data now? (y/n): ";
    $handle = fopen("php://stdin", "r");
    $line = trim(fgets($handle));
    
    if (strtolower($line) === 'y' || strtolower($line) === 'yes') {
        echo "\n";
        printInfo("Running encryption migration...");
        
        // Run migration script
        $migrationScript = __DIR__ . '/migrate_encrypt_data.php';
        if (file_exists($migrationScript)) {
            echo "\n";
            system("php " . escapeshellarg($migrationScript));
            echo "\n";
        } else {
            printError("Migration script not found: migrate_encrypt_data.php");
        }
    } else {
        printInfo("Skipped data encryption. You can run it later with:");
        echo "  " . colorOutput("php migrate_encrypt_data.php", 'cyan') . "\n";
    }
} else if ($stats['encrypted'] > 0) {
    printSuccess("Found {$stats['encrypted']} users with encrypted emails!");
} else {
    printSuccess("No existing users - encryption will be applied to new users automatically.");
}

// Step 6: Verify encryption is working
printInfo("Step 6: Verifying encryption...");

require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/encryption.php';

try {
    if (Encryption::isConfigured()) {
        // Test encrypt/decrypt
        $testData = "test@example.com";
        $encrypted = Encryption::encrypt($testData);
        $decrypted = Encryption::decrypt($encrypted);
        
        if ($testData === $decrypted) {
            printSuccess("Encryption test PASSED! ✨");
        } else {
            printError("Encryption test FAILED! Decryption mismatch.");
            exit(1);
        }
    } else {
        printError("Encryption key not configured properly.");
        exit(1);
    }
} catch (Exception $e) {
    printError("Encryption test failed: " . $e->getMessage());
    exit(1);
}

// Final summary
printHeader("Setup Complete! 🎉");

echo colorOutput("✅ Encryption key configured\n", 'green');
echo colorOutput("✅ Database structure ready\n", 'green');
echo colorOutput("✅ Encryption system verified\n", 'green');

if ($stats['encrypted'] > 0) {
    echo colorOutput("✅ {$stats['encrypted']} users encrypted\n", 'green');
}

echo "\n";
printInfo("Next steps:");
echo "  1. Test the encryption: " . colorOutput("php test_encryption.php", 'cyan') . "\n";
echo "  2. View statistics: " . colorOutput("php test_stats.php", 'cyan') . "\n";
echo "  3. Check specific user: " . colorOutput("php test_user.php admin@fitxbrawl.com", 'cyan') . "\n";

echo "\n";
printInfo("For more information, see: docs/security/AES-ENCRYPTION-GUIDE.md");

echo "\n" . str_repeat("=", 60) . "\n";
echo colorOutput("  Your local environment is ready! 🚀", 'green') . "\n";
echo str_repeat("=", 60) . "\n\n";
